# Generated by Django 4.1.2 on 2022-10-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["id"],
                "verbose_name": "Имя автора",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["id"],
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["id"],
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["id"],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["id"],
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["id"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="order_step",
            options={
                "ordering": ["id"],
                "verbose_name": "Этап",
                "verbose_name_plural": "Этапы",
            },
        ),
    ]
