# Generated by Django 4.1.2 on 2022-10-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_order_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="сontent_order",
            options={"ordering": ["id"]},
        ),
    ]
