# Generated by Django 4.1.2 on 2022-10-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_сontent_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_step",
            name="date_step_beg",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата начала этапа"
            ),
        ),
        migrations.AlterField(
            model_name="order_step",
            name="date_step_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата завершения этапа"
            ),
        ),
    ]
