# Generated by Django 4.1.2 on 2022-10-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_order_step_date_step_beg_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order_step",
            constraint=models.UniqueConstraint(
                fields=("order", "step"), name="unique_element"
            ),
        ),
    ]
